output_path: "./output_${SLURM_JOB_ID}_${NOW}"

dataset_file: datasets.mvtec

multigpu: no
mp_loaders: 8
batch_size: 64
pca_variance_percentage: 5
max_epochs: 5
preprocessing: 'normalize_last' # ['none', 'normalize_last']

optim:
    name: "Adam"
    learning_rate: 1.0e-4
    lr_function: "polynomial"
    lr_params:
        power: 1.0     # setting to 1.0 means linear decay
        min_lr_factor: 0.1 # factor times initial learning rate

architecture: 'resnet18' # ['resnet18', 'resnet101', 'vitb16', 'convnext-b', 'efficientnet']
k: 2

num_layers: 4
channel_mults: [1, 1, 1, 1]

class_label: 0
use_logger: no

load_from: /home/lars/Outliers/Nonlinear-invariants/output_${SLURM_JOB_ID}_${NOW}/